rversion: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install -g
      - npm install -g serverless
      - echo "Done!!!!!!"
artifacts:
   files:
    - '*/'